# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HpRQctXQwMXO6Xo_6u6SVBklSqaY2PtH
"""

import pandas as pd
import numpy as np

df = pd.DataFrame(pd.read_csv('/content/train (1).csv'))
df.head(15)

df.shape

df.isnull().sum()

x=df.isnull().sum()

drop_col=x[x>(50/100 * df.shape[0])]
drop_col

drop_col.index

df.drop(drop_col.index, axis=1, inplace=True)
df.isnull().sum()

df.fillna(df.mean(), inplace=True)
df.isnull().sum()

df['Embarked'].describe()

df['Embarked'].fillna('S',inplace=True)

df.isnull().sum()

df.corr()

df['FamilySize']= df['SibSp']+df['Parch']
df.drop(['SibSp', 'Parch'], axis=1, inplace=True)
df.corr()

df['Alone'] = [0 if df['FamilySize'][i]>0 else 1 for i in df.index]
df.head()

df.groupby(['Alone'])['Survived'].mean() #passengers travelling with their family have higher survival rate

df[['Alone','Fare']].corr()

df['Sex'] = [0 if df['Sex'][i]=='male' else 1 for i in df.index]
df.groupby(['Sex'])['Survived'].mean()

df.groupby(['Embarked'])['Survived'].mean()

"""# *CONCLUSION* 


1.   passengers travelling with their family have higher survival rate
2.   Female passengers were priortized over women
3.passengers who borded the ship at cherbourg,survived more in proportion then the others
4.people with high class or rich people have higher survival rate than others








"""